# Generated by Django 5.2.3 on 2025-06-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Online Availability'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description of meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price ($)'),
        ),
    ]
