# Generated by Django 5.2.3 on 2025-06-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_meal_available_alter_meal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock Count'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Online Availability'),
        ),
    ]
